name: Deploy Frontend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check for frontend directory
        id: check-dir
        run: |
          if [ -d "./frontend" ]; then
            echo "FRONTEND_PATH=./frontend" >> $GITHUB_ENV
          else
            echo "FRONTEND_PATH=." >> $GITHUB_ENV
          fi  # Closing the if block

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: ${{ env.FRONTEND_PATH }}/package-lock.json

      - name: Install dependencies
        run: |
          cd ${{ env.FRONTEND_PATH }}
          npm install

      - name: Build the frontend
        run: |
          cd ${{ env.FRONTEND_PATH }}
          npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ env.FRONTEND_PATH }}/dist

