name: Django CI

on:
  push:
    branches: [ "main", "default-pattern" ]
  pull_request:
    branches: [ "main", "default-pattern" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        cd backend
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Setup
      run: |
        cd backend
        python manage.py makemigrations users posts
        touch .env
        echo "SECRET_KEY=your_secret_key" >> .env
        echo "DEBUG=True" >> .env
        python manage.py migrate
    - name: Run Tests
      run: |
        cd backend
        python manage.py test
